language: php
php:
  - '5.6'
  - '7.0'
install:
  - composer install
addons:
    code_climate:
        repo_token: a739dbf5565c52b00aa56565081c48149802810d4c890697823ccde2fc9acf9e
after_script:
  - vendor/bin/test-reporter